version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: streamingpro_postgres_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user_streaming
      POSTGRES_PASSWORD: password_streaming
      POSTGRES_DB: streamingpro_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user_streaming -d streamingpro_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:15
    container_name: streamingpro_postgres_test_db
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: user_streaming
      POSTGRES_PASSWORD: password_streaming
      POSTGRES_DB: streamingpro_test_db
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user_streaming -d streamingpro_test_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  postgres_test_data:
    driver: local 