# Configuración mínima de MediaMTX para desarrollo
logLevel: info

# API para gestión
api: true
apiAddress: :9997

# Protocolos básicos
rtsp: true
rtspAddress: :8554

rtmp: true
rtmpAddress: :1935

hls: true
hlsAddress: :8888

webrtc: true
webrtcAddress: :8889

srt: true
srtAddress: :8890

# Configuración simple de paths
pathDefaults:
  source: publisher

paths:
  "~^(.*)$":
    source: publisher 